GET {{baseUrl}}/items/analytics?facilityId={{facilityId}}
Authorization: Bearer {{accessToken}}

GET {{baseUrl}}/dashboard/stat?facilityId={{facilityId}}
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/dashboard/soon-to-expire?facilityId={{facilityId}}
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/dashboard/usage?facilityId={{facilityId}}
Authorization: Bearer {{accessToken}}

###
# @name top-selling
GET {{baseUrl}}/dashboard/items/top-selling?dateRange=this_year
Authorization: Bearer {{accessToken}}

###
# @name least-selling
GET {{baseUrl}}/dashboard/items/least-selling?dateRange=this_year
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/dashboard/item-categories/top-selling?dateRange=this_year
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/dashboard/sales-trend?facilityId={{facilityId}}&startDate=2024-11-11&endDate=2024-12-11
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/dashboard/sales/daily?dateRange=this_month
Authorization: Bearer {{accessToken}}
