###
GET {{baseUrl}}/dashboard/soon-to-expire?facilityId={{facilityId}}
Authorization: Bearer {{accessToken}}

###
# @name general
GET {{baseUrl}}/dashboard/general?startDate=2025-05-01&endDate=2025-06-06
Authorization: Bearer {{accessToken}}

###
# @name top-selling-item
GET {{baseUrl}}/dashboard/items/top-selling?dateRange=this_year
Authorization: Bearer {{accessToken}}

###
# @name least-selling-item
GET {{baseUrl}}/dashboard/items/least-selling?dateRange=this_year
Authorization: Bearer {{accessToken}}

###
# @name top-selling-category
GET {{baseUrl}}/dashboard/item-categories/top-selling?dateRange=this_year
Authorization: Bearer {{accessToken}}

###
# @name sales trend
GET {{baseUrl}}/dashboard/sales/trend?dateRange=this_month
Authorization: Bearer {{accessToken}}

###
# @name daily sales
GET {{baseUrl}}/dashboard/sales/daily?startDate=2025-05-23&endDate=2025-06-03
Authorization: Bearer {{accessToken}}

###
# @name sales payment-methods
GET {{baseUrl}}/dashboard/sales/payment-methods?dateRange=this_month
Authorization: Bearer {{accessToken}}

###
# @name insured sales
GET {{baseUrl}}/dashboard/sales/markup?dateRange=this_month
Authorization: Bearer {{accessToken}}
