GET {{baseUrl}}/items
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/items?status=OUT_OF_STOCK
Authorization: Bearer {{accessToken}}

###
# @name search
GET {{baseUrl}}/items?pageSize=3
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/items/counts
Authorization: Bearer {{accessToken}}

###
DELETE {{baseUrl}}/items/{{search.response.body.data.rows[0].itemId}}
Authorization: Bearer {{accessToken}}
