GET {{baseUrl}}/items?facilityId={{facilityId}}
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/items?facilityId={{facilityId}}
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/items?pageSize=3&search=2
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/items/counts
Authorization: Bearer {{accessToken}}
