@baseUrl = http://localhost:5500/api/v1

GET {{baseUrl}}/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYTk4ODQ2NS05YzYyLTQzYzgtODBmZC00MjllNDU5ZGY3MWMiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwuY29tIiwiZmFjaWxpdHkiOiJmNWNiMzE3My1lYzQ2LTQ2YjgtOGNiNi1mOWFmZTljOTg2YTUiLCJkZXBhcnRtZW50IjpudWxsLCJyb2xlIjoiaG9zcGl0YWxfYWRtaW4iLCJwZXJtaXNzaW9ucyI6WyJpdGVtczpSRUFEX1dSSVRFX0RFTEVURSIsIml0ZW1fY2F0ZWdvcmllczpSRUFEX1dSSVRFX0RFTEVURSIsInN0b2NrX2FkanVzdG1lbnQ6UkVBRF9XUklURV9ERUxFVEUiLCJpdGVtX29yZGVyczpSRUFEX1dSSVRFX0RFTEVURSIsInJlcG9ydHM6UkVBRF9XUklURV9ERUxFVEUiLCJzdXBwbGllcnM6UkVBRF9XUklURV9ERUxFVEUiLCJzYWxlczpSRUFEX1dSSVRFX0RFTEVURSIsImRlcGFydG1lbnRfcmVxdWVzdHM6UkVBRF9XUklURV9ERUxFVEUiXSwic2Vzc2lvbiI6ImJmZWY0YTgwLWY0OWYtNDM4MS05NGJjLTA0YTZjYjk2ZmVmYyIsImlhdCI6MTczMjM4Mjk2NywiZXhwIjoxNzMyMzg2NTY3LCJhdWQiOiJsb2NhbGhvc3Q6NTUwMCIsImlzcyI6ImxvY2FsaG9zdDo1NTAwIn0.PUELeIxUrkD0_qLAgRiK1YgnAcpv60QoQPW0diVTqQ0# @lang=lua

